name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:

env:
  TF_WORKING_DIR: ./terraform

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Show repo contents
        run: ls -R .
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0
      - name: Terraform Init
        run: terraform init -input=false
      - name: Terraform Fmt & Validate
        run: |
          terraform fmt -check
          terraform validate
      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan -detailed-exitcode
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && steps.plan.outcome == 'success'
        run: terraform apply -auto-approve tfplan
