name: Terraform CI/CD

on:
  push:
    branches: [main]
  pull_request:

env:
  TF_WORKING_DIR: ./terraform

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"
      - name: Terraform Init
        run: terraform init -input=false
      - name: Terraform Fmt & Validate
        run: |
          terraform fmt -check
          terraform validate
      - name: Terraform Plan and Comment
        uses: dflook/terraform-plan@v1
        with:
          path: ${{ env.TF_WORKING_DIR }}
          args: -out=tfplan -detailed-exitcode
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && steps.plan.outcome == 'success'
        run: terraform apply -auto-approve tfplan